baseURL = 'https://showiproute-dev.netlify.app/' # replace with 'https://showiproute.com/'
languageCode = 'en-us'
title = 'ShowIPRoute'
theme = 'hugo-clarity'

[pagination]
pagerSize = 10

[params]
customCSS = ["css/custom.css"]